While Loop

It is variable iteration loop.

Syntax:

while condition:
  
    statements


In [1]:
i=10
j=1
while j<i:
  print(i)
  j=j+1

10
10
10
10
10
10
10
10
10


In [2]:
price=9000
i=5
while i<=20:
  dicountprice=price*(i/100)
  finalprice=price-dicountprice
  print('The discount of ',i,' % is : ',finalprice)
  i=i+5

The discount of  5  % is :  8550.0
The discount of  10  % is :  8100.0
The discount of  15  % is :  7650.0
The discount of  20  % is :  7200.0


In [3]:
# def keyword is used to define function
def myfunction():
  print('Welcome to Data Science course!')
myfunction()

Welcome to Data Science course!


In [4]:
# function with input parameters
def welcomefunction(name):
  print('Welcome ',name)


In [5]:
welcomefunction('Ravi')

Welcome  Ravi


In [6]:
# function with paramters and returns value
def sum(num1,num2,num3):
  result=num1+num2+num3
  return result

In [7]:
sum(1,2,3)

6

In [8]:
#positional argument
def total(*num):
  result=0
  for i in num:
    result=result+i
  return result

In [9]:
total()

0

In [10]:
total(1,2)

3

In [11]:
total(1,2,3,4,5)

15

In [12]:
total(1,2,3,4,5,6,7,8,9,10,11,12)

78

In [13]:
# default values in function
def simpleinterest(p,t,r=5.0):
  result=(p*r*t)/100
  return result

In [14]:
simpleinterest(100,1)


5.0

In [15]:
simpleinterest(100,1,14)

14.0

In [16]:
# importing the numpy library
# installing numpy lib in system
# pip install numpy
import numpy as np

In [17]:
#single dimensional array
single_dim_array=np.array([1,2,3,4,5])
single_dim_array

array([1, 2, 3, 4, 5])

In [18]:
type(single_dim_array)

numpy.ndarray

In [19]:
# Multi dimesnsional array
multi_dim_array=np.array([[1,1,1],[2,2,2],[3,3,3]])
multi_dim_array

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [20]:
type(multi_dim_array)

numpy.ndarray

In [21]:
# Initilaizing NumPy array with all zeros
n1=np.zeros((4,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
type(n1)

numpy.ndarray

In [23]:
#Initializing NumPy array with same number
n2=np.full((4,4),(5))
n2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [24]:
type(n2)

numpy.ndarray

In [25]:
#Initialize a NumPy array with range function
n3=np.arange(1,51)
n3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [26]:
n3=np.arange(10,101,5)
n3

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [27]:
# Initializing a NumPy array with random numbers
n4=np.random.randint(100,1000,10)
n4

array([977, 890, 470, 123, 341, 509, 611, 728, 856, 401])

In [28]:
#Checking the shapes of NumPy arrays
single_dim_array.shape

(5,)

In [29]:
multi_dim_array.shape

(3, 3)

In [30]:
# Stacking functions in NumPy
# 1. vstack()
n1=np.array([1,2,3,4,5])
n2=np.array([10,20,30,40,50])
n3=np.vstack((n1,n2))
n3

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [31]:
# 2. hstack()
n1=np.array([6,7,8,9,10])
n2=np.array([60,70,80,90,100])
n3=np.hstack((n1,n2))
n3

array([  6,   7,   8,   9,  10,  60,  70,  80,  90, 100])

In [32]:
# 3. column_stack()
n1=np.array([1,2,3,4,5])
n2=np.array([10,20,30,40,50])
n3=np.column_stack((n1,n2))
n3

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

In [33]:
# NumPy Intersection and difference
n1=np.array([10,20,30,40,50,60])
n2=np.array([30,40,50,70,80,90])
n3=np.intersect1d(n1,n2)
n3

array([30, 40, 50])

In [34]:
n3=np.setdiff1d(n1,n2)
n3

array([10, 20, 60])

In [35]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [36]:
# Addition of NumPy array
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.sum([n1,n2])

21

In [37]:
np.sum([n1,n2],axis=0)

array([5, 7, 9])

In [38]:
np.sum([n1,n2],axis=1)

array([ 6, 15])

In [39]:
# Basic Arithmetic
n1=np.array([10,20,30,40,50])
# Addition
print(n1+5)
# Substraction
print(n1-5)
#Multiplication
n1*2
#Division
n1/5    #(float division)
n1//5   #(inetger division)

[15 25 35 45 55]
[ 5 15 25 35 45]


array([ 2,  4,  6,  8, 10], dtype=int32)

In [40]:
# Mean, Median and Standard Deviation
n1=np.array([1,2,3,4,5])
#Mean=Sum of all elements/Total number of elements
np.mean(n1)

3.0

In [41]:
#Median= 1. arrange all values in ascending/descending order then the middle value is median
np.median(n1)

3.0

In [42]:
n1=np.array([10,60,50,70,20])
np.median(n1)

50.0

In [43]:
n1=np.array([1,2,3,4,5,6])
np.median(n1)

3.5

In [44]:
#Standard Deviation
np.std(n1)

1.707825127659933

In [45]:
# Saving and Loading of NumPy array
n1=np.array([50,60,70,80,10,20,30,40,50,60])
np.save('MyArray',n1)

In [46]:
#Loading the MyArray into n2 array
n2=np.load('MyArray.npy')
n2

array([50, 60, 70, 80, 10, 20, 30, 40, 50, 60])