Practice Question on NumPy

Q-1: import the library with alias np

In [2]:
import numpy as np

Q-2: Create an array of 8 eights

In [9]:
a=np.full(8,8)
a

array([8, 8, 8, 8, 8, 8, 8, 8])

In [10]:
type(a)

numpy.ndarray

Q-3: Create an array of integers from 10 to 50

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Q-4: Create a 3x3 matrix with values ranging from 22 to 30

In [15]:
np.arange(22,31).reshape(3,3)

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [16]:
arr=np.arange(26,51).reshape(5,5)
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

Q-5: Use indexing on arr to get below output

[[37,38,39,40],

[42,43,44,45],

[47,48,49,50]]

In [17]:
arr[2:,1:]

array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

Q-6: Use indexing on arr to get below output

output should be 50

In [18]:
arr[4,4]

50

Q-7: Use indexing on arr to get below output

[[27],

[32],

[37]]

In [19]:
arr[0:3,1:2]

array([[27],
       [32],
       [37]])

Q-8: Use indexing on arr to get below output

[46, 47, 48, 49, 50]

In [20]:
arr[4]

array([46, 47, 48, 49, 50])

In [21]:
arr[-1]

array([46, 47, 48, 49, 50])

Q-9: Use indexing on arr to get below output

[[41,42,43,44,45],

[46,47,48,49,50]]

In [23]:
arr[3:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [25]:
arr[3:5]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [26]:
arr[-2:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
arr=np.arange(10,40).reshape(6,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

Q-10: Find the sum of all values in given array 'arr'

In [28]:
arr.sum()

735

In [29]:
np.sum(arr)

735

Q-11: Find the standard deviation of the values in given array 'arr'

In [31]:
arr.std()

8.65544144839919

In [32]:
np.std(arr)

8.65544144839919

Q-12: Find the mean of all the values in given array 'arr

In [33]:
arr.mean()

24.5

In [34]:
np.mean(arr)

24.5

Practice Questions on Pandas Library

Q-1: Import library with alias pd

In [35]:
import pandas as pd

Q-2: Read the given .csv file

In [41]:
df=pd.read_csv('/content/sample_data/sales.csv')
df

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0              1     9796.0       5250.0     10703.0      1659.0   
1              2     8294.0       8186.0     12694.0      1461.0   
2              3    11001.0      14399.0     16991.0      1340.0   
3              4     8301.0      11188.0     12289.0      1451.0   
4              5    10510.0      12629.0     13921.0      1770.0   
..           ...        ...          ...         ...         ...   
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available       Parking Coupon_Category  Daily_Customer_Count  \
0             1961.0          Open           CAT B                   530   
1             1752.0  Not Provided           CAT B                   210   
2             1609.0  Not Provided           CAT A                   720   
3             1748.0       Covered           CAT B                   620   
4             2111.0  Not Provided           CAT B                   450   
..               ...           ...             ...                   ...   
927           1910.0       Covered           CAT C                  1080   
928           1663.0          Open           CAT A                   850   
929           1436.0          Open           CAT A                  1060   
930           1560.0          Open           CAT B                   770   
931           1429.0       Covered           CAT C                  1110   

     Store_Sales  
0          66490  
1          39820  
2          54010  
3          53730  
4          46620  
..           ...  
927        66390  
928        82080  
929        76440  
930        96610  
931        54340  

[932 rows x 10 columns]

Q-3: What are the unqiue values in the 'Parking' column?

In [38]:
df['Parking'].unique()

array(['Open', 'Not Provided', 'Covered', 'No Parking'], dtype=object)

Q-4: What is the mean store area of the given data?

In [39]:
df['Store_Area'].mean()

1511.862554112554

Q-5: What are the different columns available in the dataset?

In [40]:
df.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

Q-6: Create a new series (series1) with only the values of third row

In [42]:
series1=df.iloc[2]
series1

Observation                        3
Dist_Taxi                    11001.0
Dist_Market                  14399.0
Dist_Metro                   16991.0
Store_Area                    1340.0
Items_Available               1609.0
Parking                 Not Provided
Coupon_Category                CAT A
Daily_Customer_Count             720
Store_Sales                    54010
Name: 2, dtype: object

Q-7: Create a new dataframe (df_short) which contains first 5 rows and two two columns ("Coupon_Category" and "Store_Sales")

In [ ]:
df_short=df.loc[:4,['Coupon_Category','Store_Sales']]
df_short

In [ ]:
df_short=df.head(5)[['Coupon_Category','Store_Sales']]
df_short

In [ ]:
df_short=df.loc[[0,1,2,3,4],['Coupon_Category','Store_Sales']]
df_short

Q-8: In dataframe (df_short), replace the index with ["First Row","Second Row","Third Row","Fourth Row","Fifth Row"]

In [50]:
df_short.index=['First Row','Second Row','Third Row','Forth Row','Fifth Row']
df_short

Coupon_Category  Store_Sales
First Row            CAT B        66490
Second Row           CAT B        39820
Third Row            CAT A        54010
Forth Row            CAT B        53730
Fifth Row            CAT B        46620

Q-9: Create a dataframe (df2) with the given conditions

Dist_Metro>18000
and

Parking=Open

In [51]:
df2=df[(df['Dist_Metro']>18000) & (df['Parking']=='Open')]
df2

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
88            89    14306.0      12591.0     18029.0      1441.0   
218          219    11195.0      16650.0     18762.0      1406.0   
338          339     9308.0      18281.0     18532.0      1771.0   
742          743    12973.0      15178.0     18836.0      1542.0   
791          792    14470.0      14517.0     18178.0      1645.0   
930          931    15082.0      14700.0     19617.0      1299.0   

     Items_Available Parking Coupon_Category  Daily_Customer_Count  \
88            1723.0    Open           CAT B                   330   
218           1677.0    Open           CAT A                   480   
338           2147.0    Open           CAT C                   430   
742           1844.0    Open           CAT B                   680   
791           1963.0    Open           CAT C                   900   
930           1560.0    Open           CAT B                   770   

     Store_Sales  
88         57860  
218        61660  
338        62710  
742        51380  
791        47300  
930        96610

Q-10: What is the minimum store sales?

In [52]:
df['Store_Sales'].min()

300

Q-11: What is the standard deviation of store sales?

In [53]:
df['Store_Sales'].std()

50253.63902204523

Q-12: Group the dataset with respect to variable 'Coupon_Category' using aggregation function mean()

In [54]:
df.groupby('Coupon_Category').mean()

<ipython-input-54-4bd2a1e41bdf>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Coupon_Category').mean()


Observation    Dist_Taxi   Dist_Market    Dist_Metro  \
Coupon_Category                                                         
CAT A             476.079027  8312.645062  11332.546296  13253.390244   
CAT B             455.901370  8101.061453  10713.675978  12880.435616   
CAT C             469.512605  8310.729958  11050.603376  13116.163866   

                  Store_Area  Items_Available  Daily_Customer_Count  \
Coupon_Category                                                       
CAT A            1471.070769      1762.845679            796.018237   
CAT B            1565.709945      1831.016760            782.958904   
CAT C            1485.552743      1784.170213            775.168067   

                  Store_Sales  
Coupon_Category                
CAT A            73998.662614  
CAT B            59191.479452  
CAT C            45205.504202

Q-13: Drop the 'Parking' column from the dataframe

In [57]:
df.drop('Parking',axis=1,inplace=True)

In [ ]:
df

Q-14: Export the data to csv file without 'Parking' column.

In [59]:
df.to_csv('NewSales.csv',index=False)

In [ ]:
newdf=pd.read_csv('/content/NewSales.csv')
newdf

Q-15: Display the first 10 entries of the dataset.

In [ ]:
df.head(10)

Q-16: Display the last 7 entries of the dataset.

In [ ]:
df.tail(7)

Q-17: How many rows and columns are present in the dataset?



In [ ]:
df.shape

In [ ]:
print('Number of rows : ',df.shape[0])
print('Number of columns : ',df.shape[1])

Q-18: What are the different data types of the varables in the given dataset?

In [ ]:
df.info()

In [ ]:
df.dtypes

Q-19: Check the version of Panadas which you are using?

In [ ]:
pd.__version__

Q-20: Check is there any duplicate records present.

In [ ]:
duplicates=df.duplicated()
duplicates.sum()

In [71]:
# To remove the duplicate records
df.drop_duplicates(inplace=True)

Q-21: Checking is there any missing values in dataset.

In [ ]:
df.isnull().sum()